server {
    listen 8771;
    location / {
        proxy_pass http://192.168.3.124:8771;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }
}
